document.addEventListener("DOMContentLoaded", () => {
  // Form elements
  const ticketForm = document.getElementById("ticketForm")
  const ticketTypeSelect = document.getElementById("ticketType")
  const quantityInput = document.getElementById("quantity")
  const totalAmountSpan = document.getElementById("totalAmount")
  const cardNumberInput = document.getElementById("cardNumber")
  const expiryDateInput = document.getElementById("expiryDate")
  const cvvInput = document.getElementById("cvv")
  const successMessage = document.getElementById("successMessage")
  const backButton = document.getElementById("backButton")
  const countrySelect = document.getElementById("country")
  const citySelect = document.getElementById("city")
  const phoneInput = document.getElementById("phone")

  // Ülke telefon kodları
  const countryCodes = {
    TR: "+90",
    DE: "+49",
    US: "+1",
    GB: "+44",
    FR: "+33",
    IT: "+39",
    ES: "+34",
    RU: "+7",
    CN: "+86",
    JP: "+81",
    KR: "+82",
    IN: "+91",
    BR: "+55",
    CA: "+1",
    AU: "+61",
    NL: "+31",
    SE: "+46",
    CH: "+41",
    AE: "+971",
    SA: "+966",
    ZA: "+27",
    EG: "+20",
    NG: "+234",
    MA: "+212",
    MX: "+52",
    AR: "+54",
    CO: "+57",
    CL: "+56",
    ID: "+62",
    MY: "+60",
    TH: "+66",
    SG: "+65",
    PL: "+48",
    AT: "+43",
    BE: "+32",
    DK: "+45",
    FI: "+358",
    GR: "+30",
    PT: "+351",
    IE: "+353",
  }

  // Ülkelere göre şehirler (her ülke için 35 şehir)
  const cities = {
    TR: [
      "İstanbul",
      "Ankara",
      "İzmir",
      "Bursa",
      "Antalya",
      "Adana",
      "Konya",
      "Gaziantep",
      "Şanlıurfa",
      "Kocaeli",
      "Mersin",
      "Diyarbakır",
      "Hatay",
      "Manisa",
      "Kayseri",
      "Samsun",
      "Balıkesir",
      "Kahramanmaraş",
      "Eskişehir",
      "Denizli",
      "Sakarya",
      "Tekirdağ",
      "Muğla",
      "Trabzon",
      "Mardin",
      "Ordu",
      "Malatya",
      "Afyonkarahisar",
      "Erzurum",
      "Aydın",
      "Sivas",
      "Tokat",
      "Zonguldak",
      "Çanakkale",
      "Van",
    ],
    DE: [
      "Berlin",
      "Hamburg",
      "Münih",
      "Köln",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Leipzig",
      "Bremen",
      "Dresden",
      "Hannover",
      "Nürnberg",
      "Duisburg",
      "Bochum",
      "Wuppertal",
      "Bielefeld",
      "Bonn",
      "Münster",
      "Karlsruhe",
      "Mannheim",
      "Augsburg",
      "Wiesbaden",
      "Gelsenkirchen",
      "Mönchengladbach",
      "Braunschweig",
      "Kiel",
      "Chemnitz",
      "Aachen",
      "Halle",
      "Magdeburg",
      "Freiburg",
      "Krefeld",
      "Lübeck",
    ],
    US: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "San Francisco",
      "Charlotte",
      "Indianapolis",
      "Seattle",
      "Denver",
      "Washington DC",
      "Boston",
      "El Paso",
      "Nashville",
      "Detroit",
      "Portland",
      "Las Vegas",
      "Oklahoma City",
      "Memphis",
      "Louisville",
      "Baltimore",
      "Milwaukee",
      "Albuquerque",
      "Tucson",
      "Fresno",
      "Sacramento",
    ],
    GB: [
      "Londra",
      "Birmingham",
      "Manchester",
      "Glasgow",
      "Newcastle",
      "Liverpool",
      "Nottingham",
      "Sheffield",
      "Bristol",
      "Belfast",
      "Leicester",
      "Edinburgh",
      "Leeds",
      "Cardiff",
      "Manchester",
      "Stoke-on-Trent",
      "Coventry",
      "Sunderland",
      "Birkenhead",
      "Norwich",
      "Aberdeen",
      "Dundee",
      "Swansea",
      "Oxford",
      "Cambridge",
      "Southampton",
      "Portsmouth",
      "Plymouth",
      "Derby",
      "Reading",
      "Luton",
      "Wolverhampton",
      "Bolton",
      "Bournemouth",
      "Middlesbrough",
    ],
    FR: [
      "Paris",
      "Marsilya",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
      "Rennes",
      "Reims",
      "Le Havre",
      "Saint-Étienne",
      "Toulon",
      "Grenoble",
      "Dijon",
      "Angers",
      "Villeurbanne",
      "Le Mans",
      "Nîmes",
      "Aix-en-Provence",
      "Clermont-Ferrand",
      "Brest",
      "Tours",
      "Amiens",
      "Limoges",
      "Annecy",
      "Perpignan",
      "Boulogne-Billancourt",
      "Metz",
      "Besançon",
      "Orléans",
      "Mulhouse",
      "Rouen",
    ],
    IT: [
      "Roma",
      "Milano",
      "Napoli",
      "Torino",
      "Palermo",
      "Cenova",
      "Bologna",
      "Floransa",
      "Bari",
      "Catania",
      "Venedik",
      "Verona",
      "Messina",
      "Padova",
      "Trieste",
      "Taranto",
      "Brescia",
      "Prato",
      "Reggio Calabria",
      "Modena",
      "Parma",
      "Reggio Emilia",
      "Perugia",
      "Livorno",
      "Cagliari",
      "Foggia",
      "Ravenna",
      "Siracusa",
      "Ferrara",
      "Salerno",
      "Sassari",
      "Rimini",
      "Monza",
      "Bergamo",
      "Latina",
    ],
    ES: [
      "Madrid",
      "Barselona",
      "Valencia",
      "Sevilla",
      "Zaragoza",
      "Málaga",
      "Murcia",
      "Palma",
      "Las Palmas",
      "Bilbao",
      "Alicante",
      "Córdoba",
      "Valladolid",
      "Vigo",
      "Gijón",
      "Hospitalet de Llobregat",
      "A Coruña",
      "Granada",
      "Elche",
      "Oviedo",
      "Cartagena",
      "Badalona",
      "Terrassa",
      "Jerez de la Frontera",
      "Sabadell",
      "Móstoles",
      "Alcalá de Henares",
      "Pamplona",
      "Fuenlabrada",
      "Almería",
      "Leganés",
      "San Sebastián",
      "Burgos",
      "Santander",
      "Castellón de la Plana",
    ],
    RU: [
      "Moskova",
      "St. Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Kazan",
      "Çelyabinsk",
      "Omsk",
      "Samara",
      "Rostov-on-Don",
      "Ufa",
      "Krasnoyarsk",
      "Voronezh",
      "Perm",
      "Volgograd",
      "Krasnodar",
      "Saratov",
      "Tyumen",
      "Tolyatti",
      "Izhevsk",
      "Barnaul",
      "Ulyanovsk",
      "Irkutsk",
      "Khabarovsk",
      "Vladivostok",
      "Yaroslavl",
      "Makhachkala",
      "Tomsk",
      "Orenburg",
      "Novokuznetsk",
      "Kemerovo",
      "Ryazan",
      "Astrakhan",
      "Naberezhnye Chelny",
      "Penza",
      "Lipetsk",
    ],
    CN: [
      "Pekin",
      "Şangay",
      "Guangzhou",
      "Shenzhen",
      "Chongqing",
      "Tianjin",
      "Wuhan",
      "Dongguan",
      "Chengdu",
      "Nanjing",
      "Shenyang",
      "Hangzhou",
      "Xi'an",
      "Harbin",
      "Suzhou",
      "Zhengzhou",
      "Changsha",
      "Foshan",
      "Xiamen",
      "Ningbo",
      "Wuxi",
      "Qingdao",
      "Jinan",
      "Dalian",
      "Changchun",
      "Shijiazhuang",
      "Kunming",
      "Hefei",
      "Nanchang",
      "Nanning",
      "Taiyuan",
      "Lanzhou",
      "Ürümqi",
      "Hohhot",
      "Xining",
    ],
    JP: [
      "Tokyo",
      "Yokohama",
      "Osaka",
      "Nagoya",
      "Sapporo",
      "Kobe",
      "Kyoto",
      "Fukuoka",
      "Kawasaki",
      "Saitama",
      "Hiroshima",
      "Sendai",
      "Kitakyushu",
      "Chiba",
      "Sakai",
      "Niigata",
      "Hamamatsu",
      "Okayama",
      "Shizuoka",
      "Kumamoto",
      "Sagamihara",
      "Funabashi",
      "Hachioji",
      "Matsuyama",
      "Kanazawa",
      "Utsunomiya",
      "Kagoshima",
      "Oita",
      "Kurashiki",
      "Nagasaki",
      "Toyama",
      "Asahikawa",
      "Fukuyama",
      "Gifu",
      "Takasaki",
    ],
    KR: [
      "Seul",
      "Busan",
      "Incheon",
      "Daegu",
      "Daejeon",
      "Gwangju",
      "Suwon",
      "Ulsan",
      "Changwon",
      "Goyang",
      "Seongnam",
      "Bucheon",
      "Cheongju",
      "Ansan",
      "Anyang",
      "Namyangju",
      "Jeonju",
      "Cheonan",
      "Pohang",
      "Gimhae",
      "Gyeongju",
      "Jinju",
      "Suncheon",
      "Iksan",
      "Wonju",
      "Asan",
      "Chuncheon",
      "Gunsan",
      "Yangsan",
      "Seogwipo",
      "Andong",
      "Gumi",
      "Masan",
      "Jeju City",
      "Gangneung",
    ],
    IN: [
      "Mumbai",
      "Delhi",
      "Bangalore",
      "Hyderabad",
      "Ahmedabad",
      "Chennai",
      "Kolkata",
      "Surat",
      "Pune",
      "Jaipur",
      "Lucknow",
      "Kanpur",
      "Nagpur",
      "Indore",
      "Thane",
      "Bhopal",
      "Visakhapatnam",
      "Pimpri-Chinchwad",
      "Patna",
      "Vadodara",
      "Ghaziabad",
      "Ludhiana",
      "Agra",
      "Nashik",
      "Faridabad",
      "Meerut",
      "Rajkot",
      "Kalyan-Dombivli",
      "Vasai-Virar",
      "Varanasi",
      "Srinagar",
      "Aurangabad",
      "Dhanbad",
      "Amritsar",
      "Allahabad",
    ],
    BR: [
      "São Paulo",
      "Rio de Janeiro",
      "Brasília",
      "Salvador",
      "Fortaleza",
      "Belo Horizonte",
      "Manaus",
      "Curitiba",
      "Recife",
      "Porto Alegre",
      "Belém",
      "Goiânia",
      "Guarulhos",
      "Campinas",
      "São Luís",
      "Maceió",
      "Campo Grande",
      "Natal",
      "Teresina",
      "São Bernardo do Campo",
      "João Pessoa",
      "Santo André",
      "Osasco",
      "Jaboatão dos Guararapes",
      "Contagem",
      "Sorocaba",
      "Uberlândia",
      "Ribeirão Preto",
      "Cuiabá",
      "Aracaju",
      "Feira de Santana",
      "Joinville",
      "Londrina",
      "Juiz de Fora",
      "Ananindeua",
    ],
    CA: [
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Kitchener",
      "London",
      "Victoria",
      "Halifax",
      "Oshawa",
      "Windsor",
      "Saskatoon",
      "St. Catharines",
      "Regina",
      "Sherbrooke",
      "St. John's",
      "Barrie",
      "Kelowna",
      "Abbotsford",
      "Greater Sudbury",
      "Kingston",
      "Saguenay",
      "Guelph",
      "Moncton",
      "Brantford",
      "Thunder Bay",
      "Peterborough",
      "Cambridge",
      "Lethbridge",
      "Nanaimo",
      "Sarnia",
    ],
    AU: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Newcastle",
      "Canberra",
      "Wollongong",
      "Logan City",
      "Hobart",
      "Geelong",
      "Townsville",
      "Cairns",
      "Darwin",
      "Toowoomba",
      "Ballarat",
      "Bendigo",
      "Launceston",
      "Mackay",
      "Rockhampton",
      "Bunbury",
      "Coffs Harbour",
      "Bundaberg",
      "Wagga Wagga",
      "Hervey Bay",
      "Mildura",
      "Shepparton",
      "Port Macquarie",
      "Orange",
      "Albany",
      "Tamworth",
      "Kalgoorlie",
      "Geraldton",
      "Burnie",
    ],
    NL: [
      "Amsterdam",
      "Rotterdam",
      "Lahey",
      "Utrecht",
      "Eindhoven",
      "Tilburg",
      "Groningen",
      "Almere",
      "Breda",
      "Nijmegen",
      "Enschede",
      "Haarlem",
      "Arnhem",
      "Zaanstad",
      "Amersfoort",
      "Apeldoorn",
      "Heerlen",
      "Maastricht",
      "Dordrecht",
      "Leiden",
      "Zwolle",
      "Emmen",
      "Deventer",
      "Delft",
      "Alkmaar",
      "Leeuwarden",
      "Venlo",
      "Hilversum",
      "Oss",
      "Helmond",
      "Amstelveen",
      "Hengelo",
      "Roosendaal",
      "Purmerend",
      "Schiedam",
    ],
    SE: [
      "Stockholm",
      "Göteborg",
      "Malmö",
      "Uppsala",
      "Linköping",
      "Västerås",
      "Örebro",
      "Norrköping",
      "Helsingborg",
      "Jönköping",
      "Umeå",
      "Lund",
      "Borås",
      "Sundsvall",
      "Gävle",
      "Eskilstuna",
      "Södertälje",
      "Karlstad",
      "Täby",
      "Växjö",
      "Halmstad",
      "Luleå",
      "Kristianstad",
      "Borlänge",
      "Falun",
      "Kalmar",
      "Skövde",
      "Östersund",
      "Varberg",
      "Trollhättan",
      "Motala",
      "Landskrona",
      "Nyköping",
      "Uddevalla",
      "Härnösand",
    ],
    CH: [
      "Zürih",
      "Cenevre",
      "Basel",
      "Lozan",
      "Bern",
      "Winterthur",
      "Lucerne",
      "St. Gallen",
      "Lugano",
      "Biel",
      "Thun",
      "Köniz",
      "La Chaux-de-Fonds",
      "Schaffhausen",
      "Fribourg",
      "Vernier",
      "Chur",
      "Neuchâtel",
      "Montreux",
      "Sion",
      "Kriens",
      "Yverdon-les-Bains",
      "Zug",
      "Frauenfeld",
      "Wil",
      "Bellinzona",
      "Renens",
      "Nyon",
      "Vevey",
      "Lancy",
      "Emmen",
      "Meyrin",
      "Onex",
      "Allschwil",
      "Riehen",
    ],
    AE: [
      "Dubai",
      "Abu Dabi",
      "Sharjah",
      "Al Ain",
      "Ajman",
      "Ras Al Khaimah",
      "Fujairah",
      "Umm Al Quwain",
      "Khor Fakkan",
      "Dibba Al-Fujairah",
      "Dibba Al-Hisn",
      "Hatta",
      "Madinat Zayed",
      "Ruwais",
      "Liwa Oasis",
      "Al Dhaid",
      "Ghweifat",
      "Al Mirfa",
      "Sila",
      "Delma",
      "Al Wagan",
      "Al Quaa",
      "Al Shuwaib",
      "Al Madam",
      "Kalba",
      "Masafi",
      "Al Hayl",
      "Al Fayah",
      "Al Hamraniyah",
      "Al Tawayya",
      "Al Zubarah",
      "Al Rafaah",
      "Al Khaznah",
      "Al Yahar",
      "Al Remah",
    ],
    SA: [
      "Riyad",
      "Cidde",
      "Mekke",
      "Medine",
      "Dammam",
      "Taif",
      "Tabuk",
      "Buraidah",
      "Khamis Mushait",
      "Abha",
      "Najran",
      "Yanbu",
      "Al Khobar",
      "Sakaka",
      "Jubail",
      "Hafar Al Batin",
      "Al Ahsa",
      "Qatif",
      "Al Kharj",
      "Al Taif",
      "Al Qunfudhah",
      "Al Lith",
      "Al Wajh",
      "Al Ula",
      "Al Bukayriyah",
      "Al Rass",
      "Al Mubarraz",
      "Al Hofuf",
      "Al Mithnab",
      "Al Zulfi",
      "Al Majma'ah",
      "Al Ghat",
      "Al Duwadimi",
      "Al Aflaj",
      "Al Hariq",
    ],
    ZA: [
      "Johannesburg",
      "Cape Town",
      "Durban",
      "Pretoria",
      "Port Elizabeth",
      "Bloemfontein",
      "East London",
      "Nelspruit",
      "Kimberley",
      "Polokwane",
      "Pietermaritzburg",
      "Rustenburg",
      "Potchefstroom",
      "Upington",
      "George",
      "Bhisho",
      "Mahikeng",
      "Mbombela",
      "Middelburg",
      "Newcastle",
      "Queenstown",
      "Richards Bay",
      "Saldanha",
      "Secunda",
      "Stellenbosch",
      "Uitenhage",
      "Vanderbijlpark",
      "Vereeniging",
      "Welkom",
      "Worcester",
      "Bethlehem",
      "Kroonstad",
      "Paarl",
      "Phalaborwa",
      "Soweto",
    ],
    EG: [
      "Kahire",
      "İskenderiye",
      "Giza",
      "Şubra El-Hayme",
      "Port Said",
      "Süveyş",
      "Luksor",
      "Asyut",
      "İsmailiye",
      "Fayum",
      "Zagazig",
      "Aswan",
      "Tanta",
      "Sohag",
      "Hurghada",
      "Banha",
      "Damanhur",
      "Al Mansurah",
      "Al Minya",
      "Qena",
      "Kafr El Sheikh",
      "Arish",
      "Marsa Matruh",
      "Al Mahallah al Kubra",
      "Beni Suef",
      "6th of October City",
      "10th of Ramadan City",
      "New Cairo",
      "Sheikh Zayed City",
      "Al Obour",
      "Al Shorouk",
      "Badr",
      "Sadat City",
      "Damietta",
      "New Beni Suef",
    ],
    NG: [
      "Lagos",
      "Kano",
      "Ibadan",
      "Kaduna",
      "Port Harcourt",
      "Benin City",
      "Maiduguri",
      "Zaria",
      "Aba",
      "Jos",
      "Ilorin",
      "Oyo",
      "Enugu",
      "Abeokuta",
      "Abuja",
      "Akure",
      "Bauchi",
      "Calabar",
      "Eket",
      "Gombe",
      "Gusau",
      "Jimeta",
      "Katsina",
      "Lafia",
      "Makurdi",
      "Minna",
      "Ogbomosho",
      "Onitsha",
      "Oshogbo",
      "Sokoto",
      "Umuahia",
      "Warri",
      "Yenagoa",
      "Yola",
      "Asaba",
    ],
    MA: [
      "Kazablanka",
      "Rabat",
      "Fes",
      "Marakeş",
      "Tanca",
      "Agadir",
      "Meknes",
      "Oujda",
      "Kenitra",
      "Tetouan",
      "Safi",
      "Mohammedia",
      "El Jadida",
      "Beni Mellal",
      "Nador",
      "Settat",
      "Larache",
      "Khouribga",
      "Guelmim",
      "Berkane",
      "Taourirt",
      "Taza",
      "Essaouira",
      "Al Hoceima",
      "Sidi Slimane",
      "Souk El Arbaa",
      "Ksar El Kebir",
      "Chefchaouen",
      "Fnideq",
      "Sefrou",
      "Temara",
      "Sale",
      "Skhirat",
      "Ait Melloul",
      "Ouarzazate",
    ],
    MX: [
      "Mexico City",
      "Guadalajara",
      "Monterrey",
      "Puebla",
      "Tijuana",
      "León",
      "Juárez",
      "Culiacán",
      "Mérida",
      "Chihuahua",
      "San Luis Potosí",
      "Cancún",
      "Querétaro",
      "Hermosillo",
      "Aguascalientes",
      "Mexicali",
      "Saltillo",
      "Guadalupe",
      "Acapulco",
      "Morelia",
      "Tlaquepaque",
      "Villahermosa",
      "Xalapa",
      "Torreón",
      "Tuxtla Gutiérrez",
      "Durango",
      "Mazatlán",
      "Veracruz",
      "Ciudad Obregón",
      "Cuernavaca",
      "Tepic",
      "Campeche",
      "Oaxaca",
      "Pachuca",
      "Colima",
    ],
    AR: [
      "Buenos Aires",
      "Córdoba",
      "Rosario",
      "Mendoza",
      "San Miguel de Tucumán",
      "La Plata",
      "Mar del Plata",
      "Salta",
      "Santa Fe",
      "San Juan",
      "Resistencia",
      "Neuquén",
      "Corrientes",
      "Bahía Blanca",
      "Posadas",
      "Santiago del Estero",
      "Paraná",
      "Jujuy",
      "Formosa",
      "San Fernando del Valle de Catamarca",
      "Río Cuarto",
      "Comodoro Rivadavia",
      "Concordia",
      "San Nicolás de los Arroyos",
      "Tandil",
      "Mendoza",
      "Trelew",
      "Rafaela",
      "Olavarría",
      "Pergamino",
      "Junín",
      "Campana",
      "Cipolletti",
      "Gualeguaychú",
      "Puerto Madryn",
    ],
    CO: [
      "Bogotá",
      "Medellín",
      "Cali",
      "Barranquilla",
      "Cartagena",
      "Cúcuta",
      "Bucaramanga",
      "Pereira",
      "Santa Marta",
      "Ibagué",
      "Pasto",
      "Manizales",
      "Neiva",
      "Villavicencio",
      "Armenia",
      "Soledad",
      "Bello",
      "Valledupar",
      "Montería",
      "Sincelejo",
      "Popayán",
      "Itagüí",
      "Envigado",
      "Palmira",
      "Barrancabermeja",
      "Florencia",
      "Tuluá",
      "Dosquebradas",
      "Tunja",
      "Girardot",
      "Quibdó",
      "Yopal",
      "Riohacha",
      "Pitalito",
      "Maicao",
    ],
    CL: [
      "Santiago",
      "Valparaíso",
      "Concepción",
      "La Serena",
      "Antofagasta",
      "Temuco",
      "Rancagua",
      "Talca",
      "Arica",
      "Chillán",
      "Puerto Montt",
      "Iquique",
      "Osorno",
      "Valdivia",
      "Calama",
      "Copiapó",
      "Los Ángeles",
      "Curicó",
      "Coronel",
      "San Antonio",
      "Ovalle",
      "Linares",
      "Quillota",
      "San Felipe",
      "Melipilla",
      "Villarrica",
      "Puerto Varas",
      "Ancud",
      "Castro",
      "Punta Arenas",
      "Coquimbo",
      "San Bernardo",
      "Penco",
      "Angol",
      "San Carlos",
    ],
    ID: [
      "Jakarta",
      "Surabaya",
      "Bandung",
      "Medan",
      "Semarang",
      "Makassar",
      "Palembang",
      "Tangerang",
      "Depok",
      "Padang",
      "Malang",
      "Bekasi",
      "Denpasar",
      "Yogyakarta",
      "Bogor",
      "Batam",
      "Pekanbaru",
      "Bandar Lampung",
      "Pontianak",
      "Samarinda",
      "Balikpapan",
      "Manado",
      "Jambi",
      "Ambon",
      "Cimahi",
      "Surakarta",
      "Mataram",
      "Pangkal Pinang",
      "Jayapura",
      "Bengkulu",
      "Kendari",
      "Palu",
      "Kupang",
      "Ternate",
      "Sorong",
    ],
    MY: [
      "Kuala Lumpur",
      "Johor Bahru",
      "Ipoh",
      "Kuching",
      "Kota Kinabalu",
      "Shah Alam",
      "Petaling Jaya",
      "Melaka",
      "Kota Bharu",
      "Alor Setar",
      "Kuala Terengganu",
      "Seremban",
      "George Town",
      "Kuantan",
      "Taiping",
      "Miri",
      "Sibu",
      "Pasir Gudang",
      "Sungai Petani",
      "Klang",
      "Sandakan",
      "Tawau",
      "Ampang Jaya",
      "Kulim",
      "Batu Pahat",
      "Kajang",
      "Selayang Baru",
      "Rawang",
      "Senai",
      "Butterworth",
      "Langkawi",
      "Port Dickson",
      "Kluang",
      "Bintulu",
      "Sepang",
    ],
    TH: [
      "Bangkok",
      "Nonthaburi",
      "Nakhon Ratchasima",
      "Chiang Mai",
      "Hat Yai",
      "Udon Thani",
      "Pak Kret",
      "Khon Kaen",
      "Ubon Ratchathani",
      "Surat Thani",
      "Pattaya",
      "Phuket",
      "Nakhon Si Thammarat",
      "Chon Buri",
      "Songkhla",
      "Rangsit",
      "Yala",
      "Sakon Nakhon",
      "Rayong",
      "Lampang",
      "Khlong Luang",
      "Trang",
      "Samut Prakan",
      "Phitsanulok",
      "Ayutthaya",
      "Saraburi",
      "Ratchaburi",
      "Chiang Rai",
      "Krabi",
      "Si Racha",
      "Chanthaburi",
      "Lopburi",
      "Phetchaburi",
      "Tak",
      "Nakhon Sawan",
    ],
    SG: [
      "Singapur Merkez Bölgesi",
      "Woodlands",
      "Tampines",
      "Jurong West",
      "Hougang",
      "Sengkang",
      "Yishun",
      "Ang Mo Kio",
      "Bedok",
      "Bukit Merah",
      "Choa Chu Kang",
      "Bukit Batok",
      "Toa Payoh",
      "Serangoon",
      "Bukit Panjang",
      "Pasir Ris",
      "Clementi",
      "Queenstown",
      "Geylang",
      "Bishan",
      "Sembawang",
      "Marine Parade",
      "Punggol",
      "Kallang",
      "Novena",
      "Orchard",
      "River Valley",
      "Rochor",
      "Tanglin",
      "Museum",
      "Sungei Kadut",
      "Seletar",
      "Changi",
      "Tuas",
      "Lim Chu Kang",
    ],
    PL: [
      "Varşova",
      "Kraków",
      "Łódź",
      "Wrocław",
      "Poznań",
      "Gdańsk",
      "Szczecin",
      "Bydgoszcz",
      "Lublin",
      "Katowice",
      "Białystok",
      "Gdynia",
      "Częstochowa",
      "Radom",
      "Sosnowiec",
      "Toruń",
      "Kielce",
      "Rzeszów",
      "Gliwice",
      "Zabrze",
      "Olsztyn",
      "Bytom",
      "Ruda Śląska",
      "Rybnik",
      "Tychy",
      "Opole",
      "Dąbrowa Górnicza",
      "Elbląg",
      "Płock",
      "Wałbrzych",
      "Włocławek",
      "Tarnów",
      "Zielona Góra",
      "Chorzów",
      "Koszalin",
    ],
    AT: [
      "Viyana",
      "Graz",
      "Linz",
      "Salzburg",
      "Innsbruck",
      "Klagenfurt",
      "Villach",
      "Wels",
      "Sankt Pölten",
      "Dornbirn",
      "Wiener Neustadt",
      "Steyr",
      "Feldkirch",
      "Bregenz",
      "Leonding",
      "Klosterneuburg",
      "Baden",
      "Wolfsberg",
      "Krems an der Donau",
      "Traun",
      "Amstetten",
      "Lustenau",
      "Hallein",
      "Braunau am Inn",
      "Schwechat",
      "Spittal an der Drau",
      "Telfs",
      "Perchtoldsdorf",
      "Gmunden",
      "Sankt Veit an der Glan",
      "Enns",
      "Rankweil",
      "Hard",
      "Marchtrenk",
      "Ansfelden",
    ],
    BE: [
      "Brüksel",
      "Antwerp",
      "Gent",
      "Charleroi",
      "Liège",
      "Bruges",
      "Namur",
      "Leuven",
      "Mons",
      "Aalst",
      "Mechelen",
      "Kortrijk",
      "Hasselt",
      "Ostend",
      "Tournai",
      "Sint-Niklaas",
      "La Louvière",
      "Genk",
      "Seraing",
      "Roeselare",
      "Mouscron",
      "Beveren",
      "Dendermonde",
      "Beringen",
      "Turnhout",
      "Wavre",
      "Vilvoorde",
      "Ypres",
      "Lokeren",
      "Geel",
      "Eeklo",
      "Halle",
      "Lier",
      "Mol",
      "Tienen",
    ],
    DK: [
      "Kopenhag",
      "Aarhus",
      "Odense",
      "Aalborg",
      "Frederiksberg",
      "Esbjerg",
      "Randers",
      "Kolding",
      "Horsens",
      "Vejle",
      "Roskilde",
      "Herning",
      "Silkeborg",
      "Næstved",
      "Fredericia",
      "Helsingør",
      "Viborg",
      "Køge",
      "Holstebro",
      "Slagelse",
      "Sønderborg",
      "Svendborg",
      "Hillerød",
      "Holbæk",
      "Haderslev",
      "Ringsted",
      "Brønderslev",
      "Skive",
      "Thisted",
      "Frederikshavn",
      "Aabenraa",
      "Grenaa",
      "Nyborg",
      "Nakskov",
      "Middelfart",
    ],
    FI: [
      "Helsinki",
      "Espoo",
      "Tampere",
      "Vantaa",
      "Oulu",
      "Turku",
      "Jyväskylä",
      "Lahti",
      "Kuopio",
      "Pori",
      "Kouvola",
      "Joensuu",
      "Lappeenranta",
      "Hämeenlinna",
      "Vaasa",
      "Seinäjoki",
      "Rovaniemi",
      "Mikkeli",
      "Salo",
      "Kotka",
      "Imatra",
      "Porvoo",
      "Kokkola",
      "Rauma",
      "Lohja",
      "Kajaani",
      "Raahe",
      "Tornio",
      "Savonlinna",
      "Hyvinkää",
      "Nurmijärvi",
      "Järvenpää",
      "Mäntsälä",
      "Kirkkonummi",
      "Riihimäki",
    ],
    GR: [
      "Atina",
      "Selanik",
      "Patras",
      "Heraklion",
      "Larissa",
      "Volos",
      "Ioannina",
      "Chania",
      "Chalcis",
      "Kavala",
      "Serres",
      "Alexandroupoli",
      "Kalamata",
      "Kozani",
      "Lamia",
      "Rhodes",
      "Agrinio",
      "Katerini",
      "Corfu",
      "Trikala",
      "Komotini",
      "Drama",
      "Veroia",
      "Mytilene",
      "Pyrgos",
      "Tripoli",
      "Sparta",
      "Argos",
      "Arta",
      "Preveza",
      "Kastoria",
      "Kilkis",
      "Xanthi",
      "Grevena",
      "Igoumenitsa",
    ],
    PT: [
      "Lizbon",
      "Porto",
      "Amadora",
      "Braga",
      "Coimbra",
      "Funchal",
      "Setúbal",
      "Vila Nova de Gaia",
      "Portimão",
      "Aveiro",
      "Matosinhos",
      "Évora",
      "Faro",
      "Viseu",
      "Viana do Castelo",
      "Leiria",
      "Guimarães",
      "Odivelas",
      "Almada",
      "Vila Franca de Xira",
      "Maia",
      "Castelo Branco",
      "Covilhã",
      "Barcelos",
      "Póvoa de Varzim",
      "Oliveira de Azeméis",
      "Santo Tirso",
      "São João da Madeira",
      "Espinho",
      "Figueira da Foz",
      "Penafiel",
      "Amarante",
      "Bragança",
      "Chaves",
      "Lamego",
    ],
    IE: [
      "Dublin",
      "Cork",
      "Limerick",
      "Galway",
      "Waterford",
      "Drogheda",
      "Dundalk",
      "Swords",
      "Bray",
      "Navan",
      "Ennis",
      "Kilkenny",
      "Carlow",
      "Tralee",
      "Newbridge",
      "Naas",
      "Athlone",
      "Letterkenny",
      "Wexford",
      "Sligo",
      "Clonmel",
      "Greystones",
      "Mullingar",
      "Portlaoise",
      "Balbriggan",
      "Celbridge",
      "Arklow",
      "Cobh",
      "Longford",
      "Leixlip",
      "Tullamore",
      "Carrigaline",
      "Shannon",
      "Killarney",
      "Monaghan",
    ],
  }

  // Ülke seçildiğinde şehirleri ve telefon kodunu güncelle
  function updateCountrySelection() {
    const selectedCountry = countrySelect.value

    // Şehir seçimini güncelle
    updateCities()

    // Telefon kodunu güncelle
    if (selectedCountry && countryCodes[selectedCountry]) {
      // Eğer telefon alanı boşsa veya sadece ülke kodu içeriyorsa
      if (
        !phoneInput.value ||
        phoneInput.value.trim() === "" ||
        Object.values(countryCodes).some((code) => phoneInput.value.trim() === code)
      ) {
        phoneInput.value = countryCodes[selectedCountry] + " "
      }
      // Eğer telefon alanında başka bir ülke kodu varsa, onu değiştir
      else if (Object.values(countryCodes).some((code) => phoneInput.value.startsWith(code))) {
        const currentNumber = phoneInput.value.replace(/^\+\d+\s/, "")
        phoneInput.value = countryCodes[selectedCountry] + " " + currentNumber
      }
    }
  }

  // Şehir seçimini güncelle
  function updateCities() {
    const selectedCountry = countrySelect.value

    // Şehir seçimini temizle
    citySelect.innerHTML = ""

    if (selectedCountry) {
      // Seçilen ülkenin şehirlerini ekle
      const countryCities = cities[selectedCountry]

      // İlk seçenek
      const defaultOption = document.createElement("option")
      defaultOption.value = ""
      defaultOption.textContent = "Şehir seçiniz"
      citySelect.appendChild(defaultOption)

      // Şehirleri ekle
      countryCities.forEach((city) => {
        const option = document.createElement("option")
        option.value = city
        option.textContent = city
        citySelect.appendChild(option)
      })
    } else {
      // Ülke seçilmediğinde varsayılan mesaj
      const option = document.createElement("option")
      option.value = ""
      option.textContent = "Önce ülke seçiniz"
      citySelect.appendChild(option)
    }
  }

  // Price mapping
  const prices = {
    standard: 150,
  }

  // Calculate and update total amount
  function updateTotalAmount() {
    const ticketType = ticketTypeSelect.value
    const quantity = Number.parseInt(quantityInput.value)

    if (ticketType && !isNaN(quantity)) {
      const basePrice = prices[ticketType]
      const total = basePrice * quantity
      totalAmountSpan.textContent = `${total} TL`
    } else {
      totalAmountSpan.textContent = "0 TL"
    }
  }

  // Format card number with spaces
  function formatCardNumber(e) {
    const value = e.target.value.replace(/\s+/g, "").replace(/[^0-9]/gi, "")
    let formattedValue = ""

    for (let i = 0; i < value.length; i++) {
      if (i > 0 && i % 4 === 0) {
        formattedValue += " "
      }
      formattedValue += value[i]
    }

    e.target.value = formattedValue
  }

  // Format expiry date
  function formatExpiryDate(e) {
    let value = e.target.value.replace(/\D/g, "")

    if (value.length > 2) {
      value = value.substring(0, 2) + "/" + value.substring(2, 4)
    }

    e.target.value = value
  }

  // Allow only numbers for CVV
  function formatCVV(e) {
    e.target.value = e.target.value.replace(/\D/g, "")
  }

  // Event listeners
  countrySelect.addEventListener("change", updateCountrySelection)
  ticketTypeSelect.addEventListener("change", updateTotalAmount)
  quantityInput.addEventListener("change", updateTotalAmount)
  quantityInput.addEventListener("input", updateTotalAmount)

  cardNumberInput.addEventListener("input", formatCardNumber)
  expiryDateInput.addEventListener("input", formatExpiryDate)
  cvvInput.addEventListener("input", formatCVV)

  // Form submission
  ticketForm.addEventListener("submit", (e) => {
    e.preventDefault()

    // Basic validation
    const requiredFields = ticketForm.querySelectorAll("[required]")
    let isValid = true

    requiredFields.forEach((field) => {
      if (!field.value.trim()) {
        isValid = false
        field.classList.add("error-ob")
      } else {
        field.classList.remove("error-ob")
      }
    })

    if (isValid) {
      // Simulate form submission
      ticketForm.classList.add("hidden-ob")
      successMessage.classList.remove("hidden-ob")

      // In a real application, you would send the form data to the server here
      console.log("Form submitted successfully")
    }
  })

  // Back button
  backButton.addEventListener("click", () => {
    // In a real application, this would redirect to the homepage
    window.location.href = "index.html"
  })

  // Initialize total amount
  updateTotalAmount()

  // Initialize cities dropdown
  updateCities()
})
